build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
http/src/commonMain/kotlin/com/mirego/trikot/http/HttpConfiguration.kt
swift-extensions/TrikotHttpRequest.swift

I'll update foundation and streams dependencies once built
After reading code from memory.cpp, I think we should not use the return of `freeze` method to keep the reference as it seems boxed. I am not 💯 sure of this but I prefer to go this way to make sure we are future proof.

Upgrade to kotlin 1.3.61, Gradle 5.6.4

---

http/src/commonMain/kotlin/com/mirego/trikot/http/HttpHeaderProvider.kt
http/src/commonMain/kotlin/com/mirego/trikot/http/HttpRequest.kt
http/src/commonMain/kotlin/com/mirego/trikot/http/HttpRequestFactory.kt

Include `@JsName` to methods used on the web platform.
Without these decorators, methods are exposed with an inconsistant naming, like `request_iis1eb$(requestBuilder)` instead of `request(requestBuilder)`.

Include JsName decorator to have constant naming in JavaScript

---

android-ktx/build.gradle
android-ktx/src/main/java/com/mirego/trikot/http/android/ktx/AndroidConnectivityPublisher.kt

No actual code change had to be done.
The connectivity publisher is marked API 21+ for now.
I needed to have API 19+ in my project. I lowered it even more since there was no reason not to.
Tested it in my project with min sdk api level 19

Lower min sdk version on android

---

android-ktx/src/main/java/com/mirego/trikot/http/android/ktx/AndroidConnectivityPublisher.kt

Fixes an issue where we were not having any network state when device went offline after the ConnectivityPublisher was created.
connectivityManager.registerNetworkCallback does not callback if the device is already offline when registering.
We were performing an http request which was silently not returning any errors due to the error handling using connectivity publisher.
Tested in my project

Fix AndroidConnectivityPublisher not calling back when subscribing while offline

---

http/src/commonMain/kotlin/com/mirego/trikot/http/HttpConfiguration.kt
swift-extensions/TrikotConnectivityService.swift

Remove the default WIFI connectivity state that was set causing strange behaviours when listening to that state at app startup.
When I was starting an app with NoInternet, using this connectivity state before the real state came back from the platform caused a false WIFI state.
In my current app

Remove default connectivity state

---

android-ktx/src/main/java/com/mirego/trikot/http/android/ktx/requestFactory/KtorHttpRequestFactory.kt

Omitting the `path` part on a RequestBuilder resulted in a wrong URL on Android
The Native implementation is not affected
On the RequestBuilder object, both the path and the baseUrl are optional. This signals the user that they can be omitted.
These cases where not properly handled in the Ktor implementation of HttpRequestFactory. Passing in `http://www.mirego.com/` for `baseUrl` and nothing for `path` resulted in the following request url `http://www.mirego.com/null`. 
It could be misleading to the user and result in time lost trying to figure out why a request it not sent to the right url
Tested in my project. This should have any side effect.

Provide a default value for null baseUrl and path

---

http/src/commonMain/kotlin/com/mirego/trikot/http/HttpConfiguration.kt
swift-extensions/TrikotConnectivityService.swift

We were using the `publishSubject` instead of the `bahaviorSubject` to publish the connectivity state values. The main difference between both is that a `publishSubject` does NOT dispatch a previous value to a new subscriber but the `bahaviorSubject` does. 
This issue was causing connectivityState listeners that were subscribing too late in the application boot process to never get the initial value of the system.
Tested in my application

New connectivity subscribers now get previous published value if they subscribe after initial value is dispatched

---

android-ktx/src/main/java/com/mirego/trikot/http/android/ktx/requestFactory/KtorHttpRequestFactory.kt

Since #21 was merged, all path information was ignored in the request factory since the usage of the elvis operator was wrong. 
`requestBuilder.baseUrl ?: "" + requestBuilder.path ?: ""` translate to take only baseUrl if available  or else take only path.
This PR fix this problem by adding parentheses.

Fix elvis operator usage in KtorHttpRequestFactory for Android

---

android-ktx/build.gradle
android-ktx/src/main/java/com/mirego/trikot/http/android/ktx/requestFactory/KtorHttpRequestFactory.kt
http/build.gradle
http/src/commonMain/kotlin/com/mirego/trikot/http/HttpConfiguration.kt
http/src/commonMain/kotlin/com/mirego/trikot/http/HttpResponse.kt
http/src/commonMain/kotlin/com/mirego/trikot/http/HttpResponseExtensions.kt
http/src/commonMain/kotlin/com/mirego/trikot/http/requestPublisher/DeserializableHttpRequestPublisher.kt
swift-extensions/TrikotHttpResponse.swift

We needed to be able to access to byteArray of the httpResponse instead of only assuming the body would be a string.
This allows us to handle downloading of images/files instead of only json string payloads
Tested in my application and made sure that bodyString was still available using an HttpResponse extension.
** Also fixed some warnings and small formatting

Add bodyByteArray to Http response

---

android-ktx/src/main/java/com/mirego/trikot/http/android/ktx/requestFactory/KtorHttpRequestFactory.kt
http/src/commonMain/kotlin/com/mirego/trikot/http/HttpConfiguration.kt

This PR adds the possibility of customizing 2 additional things. 
1. In the multi-platform code, we can now provide a custom `Json` instance for request deserialization
2. In the android-ktx code, we can now provide a custom HttpClient to the KtorHttpRequestFactory
For `Json`, simply to be able to configure the parsing based on the projet requirements, in particular to specify a custom serialModule to support polymorphism
For KtorHttpRequestFactory, to allow using a different engine. By default, the Android engine is used and this engine does not use any caching. With this modification, you can use for example then OkHttp engine and add a disk cache.
Tested in my projet. I made sure the  parsing still works for Json and made sure request still fire + the passed in logging configuration is …

Add some additional configurability to Trikot.http 

---

android-ktx/src/main/java/com/mirego/trikot/http/android/ktx/requestFactory/KtorHttpRequestFactory.kt

Revert the `HttpRequestBuilder` url construction using a string instead of a UrlBuilder block.
Returning a string in the url builder block has simply no effect at all and all requests resolves to `localhost`.
Tested in previous releases using the exact same code.

Fix URL not constructed using builder

---

swift-extensions/TrikotHttpRequestFactory.swift

Currently not possible to provide a subclass of `TrikotHttpRequestFactory` tailored to an app specific requirements since the class and it's sole public method `func request(requestBuilder: RequestBuilder) -> HttpRequest` where not marked open. 
Needed to be able to return different implementations of HttpRequest depending on the context.
Actual requirements motivating this change: Using a custom HttpRequest that always uses the Cellular Network
Not really a code change since it only opens up the class to subclassing so no testing done aside from confirming that it is the required change to allow subclassing and overriding of `func request(requestBuilder: RequestBuilder) -> HttpRequest`

Mark TrikotHttpRequestFactory as open so it can be subclassed

---

swift-extensions/TrikotHttpResponse.swift

Simply making the init method of TrikotHttpResponse public and tagging it @objc so it can be created from objc code and from other modules
Needed to implement a custom httpRequestFactory using low level C code
Not really a code since it only changes the visibility of a method. Made sure that this is the required change

Expose TrikotHttpResponse init method to objc

---

README.md
http/src/commonMain/kotlin/com/mirego/trikot/http/requestPublisher/ResponseHttpRequestPublisher.kt

There are cases where you may want to get the actual HttpResponse object in return. Added a class for that.
This need arose in a project
This implementation is being use in a project

Added an HttpRequestPublisher implementation that returns the HttpResponse object (no parsing)

---

gradle.properties
http/build.gradle

Update Kotlin version to 1.4.20
Update Kotlin to `1.4.20` and bump dependencies version numbers to compatible versions using the same version of Kotlin.
Keep it up to date
No code change, untested.

Update Kotlin version to 1.4.20

---

http/build.gradle.kts

During the merge of android-ktx and main component, the exclusion of the transitive dependency on "org:reactivestreams" was lost. This resulted in build errors caused by the reactivestreams classes being included twice. (the Trikot ones and the "real" ones).
Build errors.
In a a project using 2.0.0.
- [x ] Bug fix (non-breaking change which fixes an issue)

Excluded transitive dependencies on "org.reactivestreams" to avoid duplicate classes on Android

---

swift-extensions/TrikotHttpResponse.swift

When receiving an empty http response body, we did not freeze the zero length placeholder bytearray that was created on the fly, causing unwanted crashes
Since we do not have any tests on swift-extensions, I tested the fix in my own application.

Add missing freeze on empty body causing "not frozen" crash

---

http/src/androidMain/kotlin/com/mirego/trikot/http/android/requestFactory/KtorHttpRequestFactory.kt

There is currently no straightforward way to specify HTTP timeout values. It was possible by passing the HttpClient() and configuring it outside of the factory constructor, but it would be convenient to have a more "exposed" interface.
3 new optional parameters have been added to the factory to specify the timeout values.
If not set, a default value of **10 seconds** will be used.
By default Ktor have an almost infinite timeout delay (100 seconds it seems), which is not acceptable for most of the use cases. Giving the ability to set this timeout delay AND providing a more realistic default will ease usage.
In a project
⚠️ Note that if a project relied on the infinite nature of the current HTTP implementation, new timeout could occur. Please make sure that the new default value makes sense …

Added optional parameters to the KtorHttpRequestFactory to specify timeout values.

---

CHANGELOG.md
build.gradle.kts
gradle.properties
http/build.gradle.kts
http/gradle.properties
http/src/androidMain/kotlin/com/mirego/trikot/http/android/requestFactory/KtorHttpRequestFactory.kt

- Added watchOS and macOS targets
- Updated Kotlin version to 1.5.10
- Replace deprecated calls
macOS target was needed for a project
`./gradlew build`
`#dispatch/kmp`

Update Kotlin to version 1.5.10 and add watchOS and macOS targets

---

http/src/commonMain/kotlin/com/mirego/trikot/http/connectivity/ConnectivityState.kt
swift-extensions/TrikotConnectivityService.swift

Add UNDEFINED to ConnectivityState
In order to avoid that TrikotConnectivityService publisher initial value is nil, we introduce the concept of `undefined` until the connectivity state is returned by the `Reachability` service
It it not actually needed on Android side as the connectivityState is not async
The motivation is to avoid publishing a nil value
This was tested by integrating the current branch in the Podfile and by using the snapshot in the common. Then the change was tested by changing the connectivity state. There's no real big impact and it's not a breaking change

Add UNDEFINED to ConnectivityState

---

http/build.gradle.kts
http/src/commonMain/kotlin/com/mirego/trikot/http/requestPublisher/HttpRequestPublisher.kt

The try catch was surrounding the whole PublishSubjectImpl's value dispatch flow instead of simply wrapping the response's processing. This was causing execution interruptions when an exception would occur on the same run loop deeper in the reactive chain following the http request's success.
The try catch scope has now been reduced to the response processing only, allowing for further exceptions to be properly raised.

Fix silenced exceptions when dispatching http request success result

---

http/build.gradle.kts
http/src/androidMain/kotlin/com/mirego/trikot/http/android/requestFactory/KtorHttpRequestFactory.kt
http/src/commonMain/kotlin/com/mirego/trikot/http/RequestBuilder.kt
http/src/commonMain/kotlin/com/mirego/trikot/http/requestPublisher/HttpRequestPublisher.kt
http/src/commonTest/kotlin/com/mirego/trikot/http/RequestBuilderTest.kt
http/src/jsMain/kotlin/com.mirego.trikot.http/web/WebHttpRequest.kt
swift-extensions/TrikotHttpRequest.swift

Add parameters to RequestBuilder and add centralized build url function with encoded query parameters
Before, the url was "manually" built at different place. Also query parameters weren't encoded
Also put in place the test unit framework to test the new code
It's not a breaking change because the old way (using the path) will still work for valid or manually encoded url
The goal was to encode the query parameters in a centralized function.
Before, when there was an "invalid" character in a query parameter (like a space), the URL could not be built in the `execute` function of `TrikotHttpRequest.swift` and an error was returned
- The new code is unit tested
- It was tested in a project with a api call needing a json query parameter

Add encoded parameters to RequestBuilder
